Refactor git-all-repos to use find with while loop

diff --git a/bin/git-all-repos b/bin/git-all-repos
--- a/bin/git-all-repos
+++ b/bin/git-all-repos
@@ -3,31 +3,33 @@
 set -euo pipefail
 
 git-all-repos() {
-	local __current_dir=$1
-	local __git_cmd=$2
-	local __git_args=${@:3}
+  local __current_dir=$1
+  local __git_cmd=$2
+  local __git_args=${@:3}
 
-	echo "Pulling in latest changes for all repositories..."
+  echo "Pulling in latest changes for all repositories..."
 
-	for repo in $(find . -type d -name ".git" -print0 | xargs -0 -n1 dirname); do
-		cd "$repo"
+  find . -type d -name ".git" -print0 | \
+  while IFS= read -r -d '' _repo; do
+    _dir=$(dirname "$_repo")
+    cd "$_dir" || { echo "Failed to cd into: $_dir"; exit 1; }
 
-		if [ $(git remote | wc -l) -gt 0 ]; then
-			echo ""
-			echo "$(tput setaf 2)"$repo"$(tput sgr0)"
-			if [ -z "$__git_args" ]
-			then
-				git branch | awk '{print $2}' | xargs git $__git_cmd origin
-			else
-				git $__git_cmd $__git_args
-			fi
-		fi
+    if [ $(git remote | wc -l) -gt 0 ]; then
+      echo ""
+      echo "$(tput setaf 2)"$_dir"$(tput sgr0)"
+      if [ -z "$__git_args" ]
+      then
+        git branch | awk '{print $2}' | xargs git $__git_cmd origin
+      else
+        git $__git_cmd $__git_args
+      fi
+    fi
 
-		cd $__current_dir
-	done
+    cd "$__current_dir"
+  done
 
-	echo ""
-	echo "Completed!"
+  echo ""
+  echo "Completed!"
 }
 
 git-all-repos $(pwd) $@
